### ISSUE TITLE
Simple electric system

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#126]
Hi!
After adding the electric switches now, I'd like to ask which of the instruments need electrical power?

ATM I'm doing it like this:

![flowchart](https://cloud.githubusercontent.com/assets/12275960/24658714/cf0a543a-194a-11e7-8663-79c1f65b0219.png)
(done by draw.io)

Is this correct? Or are the front and rear circuits independent?

![flowchart2](https://cloud.githubusercontent.com/assets/12275960/24658861/425f2582-194b-11e7-8a58-e6b1f03fba9f.png)
(done by draw.io)

**Comment by viktorradnai** [comment]
Yes. For the turn and slip indicator to work, both panel switches need to
be on. The radio and electric vario both have their own on-off switches on
the device. Since the turn and slip indicator doesn't have one, the extra
switch is added to the panel. The master switch disconnects the battery
from the system so it switches off everything.

On 4 Apr 2017 14:17, "D-ECHO" <notifications@github.com> wrote:

Hi!
After adding the electric switches now, I'd like to ask which of the
instruments need electrical power?

ATM I'm doing it like this:

Battery -> Master Switch -> AR-3201 (comm)
-> e-vario
-> turnslip switch -> turnslip indicator

Is this correct?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/viktorradnai/flightgear-ask21/issues/126>, or mute the
thread

**Comment by ghost** [comment]
And is the front master switch for the front panel only or for both?

**Comment by gilbertohasnofb** [comment]
@D-ECHO very nice diagrams by the way

**Comment by ghost** [comment]
Partly done in fabf4a2fa864aed98c6eb9ce0a372625e4660a0a

**Comment by viktorradnai** [comment]
There are a couple of outstanding issues with the electrical system and this seems like a good place to make note of them.

1. The slip ball does not work unless the turn and slip coordinator has been powered on. Obviously that ball is an entirely mechanical device that should always "work".
2. The electric vario should not beep until the master switch has been turned on.

**Comment by ghost** [comment]
Should be fixed by a9e754526b1224e365f0b71728b78738976fe6a1

**Comment by viktorradnai** [comment]
This looks almost perfect now, the only outstanding problem is that the turn/slip coordinator needle does not return to the middle if the power is turned off while in a turn. It will just stay where it was when you turned it off.

**Comment by ghost** [comment]
Does the RL turn needle return to the middle, I though it would probably just stay if there's no power

**Comment by viktorradnai** [comment]
I would assume that there is a spring that pulls it back and the forces generated by a rotating gyro pull it out to the side when turning. But it needs testing.

**Comment by ghost** [comment]
According to http://walter.bislins.ch/aviatik/index.asp?page=Wendezeiger, the needle returns to its normal position pulled by a spring, so I'll model it like this. Question is, should we also simulate that the gyro rotates still for some time even with electricity cut off?

**Comment by viktorradnai** [comment]
It would be nice to. Some other aircraft must have already implemented
this.

**Comment by ghost** [comment]
actually the instrumentation code of flightgear already implements a simulation of the gyro, but with the needle going to -2.5 instead of anticipated 0 when gyro stops spinning
![fgfs-screen-669](https://user-images.githubusercontent.com/12275960/34372927-5de690d8-ead8-11e7-89a5-6be16cfcf85d.png)
Still, I guess there's a reason for it so I'll use that system, only thing to be modified is the turn switch to cut power from the turn indicator instead of just stucking the needle

**Comment by ghost** [comment]
see #153
