### ISSUE TITLE
Add new winch/aerotow control system as suggested on mailing list

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#18]
Hi Viktor, 
I really like the ideas you expressed on the mailing list, once we have it implemented here I will add it to every glider I made/improved (ASK13, LS8, DG1001 +all to come)

**Comment by viktorradnai** [comment]
I'm copying the proposed list of changes from the email for easier reading:

I'd like to propose a change to the glider launching. Currently most gliders in Flightgear use the following keys:

Ctrl-w: place winch in front of glider and attach cable
w: gradually increase winch speed if pressed, gradually decrease winch speed if released
Shift-w: open hook to release winch cable
Ctrl-o: find nearby aircraft capable of aerotow and attach cable
o: lock aerotow hook (to what?)
Shift-o: open aerotow hook, release cable.

So there are three keys to do the job of one and one is doing the job of two. On all the gliders I have seen so far, there is only one handle to release the cable. You pull it, both hooks open, you let go, both hooks close. This can be implemented with a single button, and for the work-in-progress ASK21 I have changed the "o" key and button 0 on the first joystick to do that:
https://github.com/viktorradnai/flightgear-ask21

Attaching the cable still needs Ctrl-w and Ctrl-o because you need to tell Flightgear which cable to attach.

This frees up the Shift-w button and I would like to use that to control the winch speed directly -- w to speed up by a fixed amount, shift-w to slow down by a fixed amount. Since winches have a throttle lever, this should work a bit better, without going into the trouble of simulating engine torque, cable friction, etc. At some point I'd also like to write a winch control AI but that's a longer story and I need to find out how the winch drivers at my club do it.

So I'm proposing the following schema:

Ctrl-w: place winch in front of glider and attach cable
w: speed up winch by 5%
Shift-w: slow down winch by 5%
Ctrl-o: find nearby aircraft capable of aerotow and attach cable
o: open both hooks on keypress, close both hooks on mod-up
Shift-o: not used

First (or second) joystick button: same as the 'o' key.

**Comment by viktorradnai** [comment]
Before we implement this everywhere I'd like to review $FGDATA/Nasal/towing/hitch.nas to see if there are more useful utility functions there that we could use. There are things like towing.closeHitch() and towing.releaseHitch() which might be used instead of modifying the properties.

**Comment by viktorradnai** [comment]
Implemented in #52
