### ISSUE TITLE
Add rudder pedals

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#67]
![Front pedals](http://www.alexander-schleicher.de/wp-content/uploads/2015/03/21-Cockpit-004.jpg)
![Front pedals 2](https://sfg-singen.de/bilder/flugzeuge/ASK21_Cockpit_vorne_kl.jpg)
![Rear pedals](http://www.aerosoft.de/shop-rd/bilder/screenshots/fsx/ask21-glider/ask21-glider-06.jpg)
(last one is simulated by aerosoft, I couldn't find a photo of the rear pedals)

**Comment by ghost** [comment]
see #65

**Comment by viktorradnai** [comment]
![20161203_194121](https://cloud.githubusercontent.com/assets/4738178/22404695/3ac96fd0-e62e-11e6-9177-9bbb50af7bf7.jpg)
Here's a pic of the rear pedals from an ASK21 in the workshop with all the internal covers removed. I've added a few more pics to the Google Drive folder I've shared with you as well.

You have the wrong idea with the rudder pedals. These are similar to the SF-25 in the way that they are hinged on a metal tube at the bottom and pivot around the Y axis not the Z axis. It's a rather clever mechanism, using steel cables but still allowing the pedals to be adjusted back and forth to accommodate various pilot sizes. 

This is how it works. The pedals have an S shaped metal tube welded onto their sides. The steel cable is threaded through the tube and it slides around freely. The cables are anchored to a fixed point in front of the pedals. Towards the back, the cables run on the side of the fuselage to a point next to the instructor seat where the cables for the front and rear pedals are joined together with a cable running to the rudder pedals. The cables are under tension by some springs, most importantly the ones built into the pedals that want to tilt the pedals forward. Since tilting the pedals forwards makes the cable run distance longer, this tightens the cables.

When you push both pedals back or pull them forward to adjust them before flight, the cable slides through the S bend and the apparent length does not change. When you press on one of the pedals, the S bend tilts, and lengthens the cable run on that side, which pulls on the cable. This causes the cable to pull the rudder to one side, which in turn pulls the other cable against the tightening springs on the opposite pedal(s), making the other pedal come backwards. The other pilot's pedals will follow this motion as the springs work to take up available slack. 

Hope this explanation makes sense, it might help if you try to visualise it.

BTW, the front and rear pedals work identically, but the front ones are close together due to the narrowing of the fuselage while the ones in the rear are spaced wide apart to fit around the seat pan of the front seat. Also the front rudder has a cable pull mechanism to unlock it (releasing a spring loaded pin that normally grabs one of several holes drilled into a metal tube laid along the X axis that the entire pedal mechanism can slide back and forth on. The rear pedal has the triangular metal rod assembly, normally held down by springs so it grabs into holes in the floor (I think). The back of this triange can be lifted up by the handle and slid back and forth, making the pedals slide inside cutouts in the pair of flat metal bars that you can see on the photo.

**Comment by ghost** [comment]
Wow, thanks for this explanation!

Am 29.01.2017 um 15:45 schrieb Viktor Radnai:

**Comment by viktorradnai** [comment]
Looks good, except for the rear pedals are too close together. And the pipe they are hinged on actually visibly connects them together. And you are missing the triangle with the handle that is used for adjustment. So nearly there.

**Comment by ghost** [comment]
improved :D see #68
