### ISSUE TITLE
Fuselage is too dark

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#83]
Particulary in shadows

**Comment by gilbertohasnofb** [comment]
See @viktorradnai pictures posted at https://github.com/viktorradnai/flightgear-ask21/pull/82#issuecomment-285986993

**Comment by viktorradnai** [comment]
The fuselage looks great in sunshine but it's too dark and has an unnatural metallic shine when it's in the shade. See how the tug aircraft (DR400) looks in comparison, it's much more natural.

![fgfs-screen-245](https://cloud.githubusercontent.com/assets/4738178/23854544/c3c64d4e-07e9-11e7-956f-0775fa65fca0.png)
![fgfs-screen-246](https://cloud.githubusercontent.com/assets/4738178/23854467/8d7b471c-07e9-11e7-8cb2-28127d859b93.png)
![fgfs-screen-248](https://cloud.githubusercontent.com/assets/4738178/23854470/8d91c6fe-07e9-11e7-92d0-52cdcb958d36.png)
![fgfs-screen-249](https://cloud.githubusercontent.com/assets/4738178/23854469/8d8a4564-07e9-11e7-9a87-9e76b0ac7326.png)
![fgfs-screen-250](https://cloud.githubusercontent.com/assets/4738178/23854468/8d8a019e-07e9-11e7-95ba-30550abcbedf.png)

**Comment by viktorradnai** [comment]
I rememebered using ambient-correction to try and fix this in the past but I cannot find any trace of having committed that in. I'll have another go unless you guys feel like doing it.

**Comment by viktorradnai** [comment]
Setting ambient-correction to 0.1 looks better. See screenshots:
![fgfs-screen-254](https://cloud.githubusercontent.com/assets/4738178/23855154/8c18a9ac-07ec-11e7-8d8d-3db79c04709d.png)
![fgfs-screen-257](https://cloud.githubusercontent.com/assets/4738178/23855155/8c1c0be2-07ec-11e7-820f-7d82132e0c87.png)

**Comment by viktorradnai** [comment]
I think the shininess needs to be reduced. This is a tricky one because gliders are shiny but only when the light hits them at an angle. The white coat diffuses reflections but it has a layer of clear coat on top which behaves similarly to water: it reflects light hitting at low angles but lets them pass through if they come in at a steep angle (close to perpendicular to the surface). Therefore it's shiny when a surface is at at an angle but not so shiny when it's looked at flat. I think the current reflections are the opposite, they are shiny when the light is perpendicular, not shiny (and slightly dark) otherwise.

@D-ECHO @gilbertohasnofb what do you think?

![Uploading fgfs-screen-258.png…]()
![fgfs-screen-259](https://cloud.githubusercontent.com/assets/4738178/23855350/3851e1ca-07ed-11e7-8c39-4201a857506c.png)
![fgfs-screen-261](https://cloud.githubusercontent.com/assets/4738178/23855351/38541ecc-07ed-11e7-8a28-8ae527645bad.png)
![fgfs-screen-262](https://cloud.githubusercontent.com/assets/4738178/23855352/38544488-07ed-11e7-81df-1d5733a4ae26.png)

**Comment by ghost** [comment]
Maybe this can be of help? http://wiki.flightgear.org/ALS_technical_notes#Glossy_surfaces It says something about angles and reflections ;)

**Comment by viktorradnai** [comment]
@D-ECHO, thanks for that. That page and the reference (https://sourceforge.net/p/flightgear/fgdata/ci/next/tree/Docs/model-combined.eff/README.model-combined.eff) did help but the best trick was this code: https://forum.flightgear.org/viewtopic.php?f=47&t=30175&sid=6c8b34784cb4061baff97367f53c72a2&start=15#p292338

I've added this to our model, not sure if I should commit it but it's definitely useful for tweaking. 

BTW, the fuselage has different reflectivity properties to the wing. Is there a good reason for this? I think they should be identical. I've got some promising settings, I can create a branch and commit them but I think I'd get better results if both materials are the same.

**Comment by viktorradnai** [comment]
OK, I think I have it nailed :)

![fgfs-screen-283](https://cloud.githubusercontent.com/assets/4738178/23880370/359913dc-084b-11e7-9453-4b554b960a49.png)

**Comment by viktorradnai** [comment]
OK, looking top down the wing still looks way too shiny when under a cloud, wonder if there is a reflection map to blame for this. From every other angle it looks pretty sweet, so I'm going to create a PR for this.

**Comment by viktorradnai** [comment]
![fgfs-screen-288](https://cloud.githubusercontent.com/assets/4738178/23880867/682d670a-084e-11e7-8171-6017ed02286f.png)

**Comment by gilbertohasnofb** [comment]
@viktorradnai 

> OK, I think I have it nailed :)

Yes you did, that looks stunning!

**Comment by gilbertohasnofb** [comment]
Once this is merged, someone could post some screen shots at the forum as this is looking _really_ good!

**Comment by viktorradnai** [comment]
![fgfs-screen-285](https://cloud.githubusercontent.com/assets/4738178/23910619/3efa8cda-08d2-11e7-9a13-4ac36ae76db6.png)
![fgfs-screen-286](https://cloud.githubusercontent.com/assets/4738178/23910620/3efc6c1c-08d2-11e7-8be5-2c1fd9a04604.png)

Here's a couple, but I'd encourage you to take a few more yourself. You get the best results with dawn / dusk light reflecting off the fuselage at a shallow angle, a scenario that is not hugely common in gliding but looks pretty sweet :)

**Comment by viktorradnai** [comment]
I'm going to close this and open another one to make the fuselage / wing material properties (reflectivity) the same.
