### ISSUE TITLE
Instrument lights are always on

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#90]
It seems to me that some gauges have the instrument lights always on, does anyone know anything about this?

**Comment by ghost** [comment]
I will fix the mapping things tomorrow. the Instrument Light is to make 
Instruments better readable



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm>


--- Original-Nachricht ---
Von: Gilberto Agostinho
Betreff: [viktorradnai/flightgear-ask21] Instrument lights are always on 
(#90)
Datum: 13.03.2017, 21:26 Uhr
An: viktorradnai/flightgear-ask21
Cc: Subscribed



It seems to me that some gauges have the instrument lights always on, does 
anyone know anything about this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/viktorradnai/flightgear-ask21/issues/90> , or mute the 
thread

**Comment by gilbertohasnofb** [comment]
@D-ECHO :+1: And so this means that once the mapping is fixed then the lights can be toggled off?

**Comment by ghost** [comment]
Actually not. I've been told by some fg glider pilots never to remove the instrument light as it was told to be important for readability.

**Comment by gilbertohasnofb** [comment]
@D-ECHO I see, so you mean this is actually a feature and is something used in RL? I never heard of it :scream: :smile: :+1:

**Comment by viktorradnai** [comment]
![fgfs-screen-289](https://cloud.githubusercontent.com/assets/4738178/23910499/d844960c-08d1-11e7-8112-da442b3248fd.png)
@D-ECHO @gilbertohasnofb I'm not sold on the idea of having them on. Can we at least turn them down a bit? I've tried to picture the worst case scenario for visibility here. Flying straight into the sun and zoomed out quite far. I can see how the lights help but maybe the effect could be made a bit more subtle? Or at least have everything look the same :D

**Comment by ghost** [comment]
I think we can add a menu option do en-/disable them and yes, I will add them to every instrument for commonality

**Comment by gilbertohasnofb** [comment]
@D-ECHO Also, take for instance the AR-3201, every single part of the instrument is being lit, including the background and all white labels. I think that if that instrument does indeed have some form of light, it would be applied only to parts of it, right?

**Comment by gilbertohasnofb** [comment]
Also, can anyone find a picture of the cockpit showing the instruments with backlight on? The pictures I have seen show no light at all, so it's difficult to judge if our effect is correct or not.

**Comment by ghost** [comment]
@gilbertohasnofb This is NOT present in RL, it's only added into fg for convenience

**Comment by gilbertohasnofb** [comment]
I see now, you wrote "fg glider pilots" but I simply read "glider pilots". Oh well, that changes everything then

**Comment by gilbertohasnofb** [comment]
Closed via #95
